### ISSUE TITLE
Sell to late

### ISSUE THREAD

**Issue by crack00r** [TheRoboKitten/ZenAii#10]
Bot still sell the coin way to late on pricedrop

**Comment by TheRoboKitten** [comment]
Please implement the script I sent you into trader.py ;) They will need to be combined. I might remove the overall macd from the base of this project, and set and instant sell order  with 1% markup for you guys over at the other telegram group.

**Comment by robsske** [comment]
What is the Telegram group and can you send the script to me also?

**Comment by TheRoboKitten** [comment]
https://cryptoping.tech/

https://cryptoalert.wordpress.com/

Also, crack00r, try pulling now. I did some edits to the bid/ask prices. (basicaly a reversal)

I lowered my percentage sell and set markup to 0pct on buy.
