### ISSUE TITLE
Poloniex API is down Error

### ISSUE THREAD

**Issue by ALaPlaceO** [TheRoboKitten/ZenAii#12]
HI, Ive ubuntu on virtualbox on desktop.
Everything worked with connecting Telegram. when clicking eg. #LTC coin into cryptoping the Aii-Bot reacts and wants to buy via Poloniex then error appears: 

"Poloniex API is down! unable to call getBalance... Invalid API key/secret pair". 

I havent implemented Poloniex key, because I want to buy only on bittrex and in conf-sample.js key is only set up therefore. so does the bot only work on poloniex at the moment or is this an error?

thx for help

**Comment by TheRoboKitten** [comment]
It only works on poloniex, but you might be able to configure it to have the regexes modified like this: 
```
                    var = word
                    var1 = var.replace('#', '')
                    btc = '-BTC'
                    variable = var1 + btc
```

to the bittrex format... not sure if it is reversed. 

then edit these: 
```
'./zenbot.sh sell/buy --order_adjust_time=1000000000 --sell_pct=100 --markup_pct=0  bittrex.' + variablestr
```

I am unsure if zenbot supports bittrex though at the moment.

You will also need to input all of the coin pairs (I used notepad ++ to make the current string):

This is for polo:
```
        #INPUT YOUR KEYWORDS BELOW
        word_list = ["#DCR", "#LTC", "#NAUT", "#NXT", "#XCP", "#GRC", "#REP", "#PPC", "#RIC", "#STRAT", "#GAME", "#BTM", "#CLAM", "#ARDR", "#BLK", "#OMNI", "#SJCX", "#FLDC", "#BCH", "#POT", "#VRC", "#ETH", "#PINK", "#NOTE", "#BTS", "#AMP", "#NAV", "#BELA", "#ETC", "#FLO", "#VIA", "#XBC", "#XPM", "#DASH", "#XVC", "#GNO", "#NMC", "#RADS", "#VTC", "#XEM", "#FCT", "#XRP", "#NXC", "#STEEM", "#SBD", "#BURST", "#XMR", "#DGB", "#LBC", "#BCY", "#PASC", "#LSK", "#EXP", "#MAID", "#BTCD", "#SYS", "#GNT", "#HUC", "#EMC2", "#NEOS", "#ZEC", "#STR"]
```

**Comment by ALaPlaceO** [comment]
thx for that, merely I have no clue how to replace it. would be really great if you could update this for bittrex. 

why is it even configured for poloniex? when I look at the cryptoping signals they never rise more than about +5% in total..my settings are intraday for signal frequency and ping to show up from 1/7 to 4/7. do you get better results for poloniex? if yes how is your cryptoping configured? would be great if you could tell if so. 

on bittrex I almost everyday get results like around +10%, which seems much better for trailing strategy, when using with eg. 8% trailing (using less trailing % never worked well on my analysis, since selling happens when pump is going on in little waves with around max. 7,5% on average downs inbetween)
