### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by crack00r** [TheRoboKitten/ZenAii#3]
isnt there any status like
https://camo.githubusercontent.com/1b4c5362cb5567b3ccc50cd6a83a1acb6c048f4e/68747470733a2f2f7261776769742e636f6d2f6361726c6f7338662f7a656e626f742f6d61737465722f6173736574732f636f6e736f6c652e706e67

**Comment by TheRoboKitten** [comment]
Unfortunately there won't be a status until  I can sort out all the zenbot engine.js issues. The status is part of the trader command on zenbot but here we just use the sell and buy commands to avoid the need to kill a node process and sell in a while loop. (this likely wouldn't work unfortunately.) Though, at some point I might switch to using poloniex-api to move away from zenbot on this, but starting a new job soon so I might not have time :)

**Comment by crack00r** [comment]
pls reopen this
