### ISSUE TITLE
Only buy once

### ISSUE THREAD

**Issue by crack00r** [TheRoboKitten/ZenAii#9]
multicoin didnt work, and after slled a coin, didnt buy into new coin

**Comment by TheRoboKitten** [comment]
I know this thing has tons of bugs currently :( I am starting a  new job this monday, so my overall time developing this will slow down dramatically.

**Comment by TheRoboKitten** [comment]
Basically, I have everything set to buy 100pct now by programming. The trader.py is not that functional yet, but I might include this in the future :) You could technically mod it now though, just remove the coin.run functions. (where it reads the pid and creates coin.run and checks it in the if statement at the beginning function. 
```
            if word in result_set:
                try:
                    var = word
                    var1 = var.replace('#', '')
                    btc = '-BTC'
                    variable = var1 + btc
                    m = multiprocessing.Process(target = runitt , args = ())
                    m.start()
                    client(ForwardMessageRequest(peer=peer1, id=(idd), random_id=(generate_random_long())))
                except Exception as e:
                    print(e)
```
Remove:     
```
open(pid, 'w').close()
```
and
```
os.remove(pid)
```
